# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
 - package-ecosystem: "pip"
   directory: "/"
   schedule:
     interval: "weekly"
   allow:
     - dependency-name: "twitchAPI"
       dependency-type: "production"
     - dependency-name: "discord.py"
       dependency-type: "production"
     - dependency-name: "PyYAML"
       dependency-type: "production"
     - dependency-name: "psycopg2"
       dependency-type: "production"
