client:
        token: 'NjIwNDc0OTkyNjA5NzIyMzg3.XeqnHQ.VEVIet_AWLFWlqnW6D3yUgHhZj4'
        chan_id: 338723133462806528
twitch:
        client_id: '5mh255cedulq2be7xrm3147msuv5k8'
        secret: 'kcvo5nw8xtdhhl61d77welj7wvvopy'
        twitch_logins: ['lesgueteuses', 'bololtv', 'siraza', 'papydje']
        chan_id: 341546425051643907